# Generated by Django 5.2 on 2025-04-26 15:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ani_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('jtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('native', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('thumbnail', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('views', models.BigIntegerField(default=0)),
                ('studio', models.CharField(blank=True, default='Mappa', max_length=255, null=True)),
                ('format', models.CharField(choices=[('TV', 'Tv'), ('TV_SHORT', 'Tv Short'), ('MOVIE', 'Movie'), ('SPECIAL', 'Special'), ('OVA', 'Ova'), ('ONA', 'Ona'), ('MUSIC', 'Music'), ('MANGA', 'Manga'), ('NOVEL', 'Novel'), ('ONE_SHOT', 'One Shot')], default='TV', max_length=255)),
                ('status', models.CharField(choices=[('FINISHED', 'Finished'), ('RELEASING', 'Releasing'), ('NOT_YET_RELEASED', 'Not Yet Released'), ('CANCELLED', 'Cancelled'), ('HIATUS', 'Hiatus')], default='FINISHED', max_length=255)),
                ('synonyms', models.JSONField(default=list)),
                ('average_score', models.IntegerField(blank=True, default=0, null=True)),
                ('mean_score', models.IntegerField(blank=True, default=0, null=True)),
                ('popularity', models.IntegerField(blank=True, default=0, null=True)),
                ('favorites', models.IntegerField(blank=True, default=0, null=True)),
                ('trending', models.IntegerField(blank=True, default=0, null=True)),
                ('banner', models.URLField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('chapters', models.IntegerField(blank=True, null=True)),
                ('episodes_count', models.IntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=20, null=True)),
                ('season_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('jtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('duration', models.SmallIntegerField(blank=True, null=True)),
                ('thumbnail', models.JSONField(default=dict)),
                ('video_url', models.URLField()),
                ('episode_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AnimeGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Ecchi', 'Ecchi'), ('Fantasy', 'Fantasy'), ('Hentai', 'Hentai'), ('Horror', 'Horror'), ('Mahou Shoujo', 'Mahou Shoujo'), ('Mecha', 'Mecha'), ('Music', 'Music'), ('Mystery', 'Mystery'), ('Psychological', 'Psychological'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci Fi'), ('Slice of Life', 'Slice Of Life'), ('Sports', 'Sports'), ('Supernatural', 'Supernatural'), ('Thriller', 'Thriller')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AnimeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='AnimeComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='anime.anime')),
            ],
        ),
    ]
