# Generated by Django 5.2 on 2025-04-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
