# Generated by Django 5.2 on 2025-04-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_country_of_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='ani_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
