# Generated by Django 5.2 on 2025-04-26 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_ani_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='banner',
            new_name='banner_image',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='favorites',
            new_name='favourites',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='volume',
            new_name='volumes',
        ),
    ]
